FROM node:22.12.0

WORKDIR /app

COPY . .

RUN yarn install

EXPOSE 3000

CMD ["yarn", "start:dev"]

# COPY package.json yarn.lock ./
# COPY prisma ./prisma

# RUN yarn install

# RUN yarn build

# RUN npx prisma generate

# COPY . .

# EXPOSE 3000

# CMD ["node", "dist/main.js"]

